"""
Database Models

Defines data models for the web application.
For this demo, we use in-memory storage, but these models
are designed to be compatible with SQLAlchemy or similar ORMs.
"""

from dataclasses import dataclass, field
from datetime import datetime
from typing import Optional, List
from enum import Enum


class ThreatType(Enum):
    """Types of detected threats."""
    BENIGN = "benign"
    SQL_INJECTION = "sql_injection"
    XSS = "xss"
    DDOS = "ddos"
    BOT = "bot"
    UNKNOWN = "unknown"


@dataclass
class User:
    """User model."""
    id: int
    username: str
    email: str
    created_at: datetime = field(default_factory=datetime.utcnow)
    is_active: bool = True


@dataclass
class Product:
    """Product model."""
    id: int
    name: str
    description: str
    price: float
    stock: int = 0
    created_at: datetime = field(default_factory=datetime.utcnow)


@dataclass
class RequestLog:
    """
    Model for logged HTTP requests.

    Used for ML training data generation.
    """
    id: int
    timestamp: datetime
    request_id: str
    method: str
    path: str
    source_ip_hash: str
    response_code: int
    duration_ms: float
    features: dict
    label: Optional[ThreatType] = None
    model_prediction: Optional[ThreatType] = None
    confidence: Optional[float] = None


@dataclass
class WAFRule:
    """
    Model for WAF rules generated by the ML model.
    """
    id: str
    name: str
    description: str
    rule_type: str
    pattern: str
    action: str
    priority: int
    created_at: datetime = field(default_factory=datetime.utcnow)
    created_by: str = "federated_learning"
    is_active: bool = True
    confidence_score: float = 0.0


@dataclass
class FederatedModelUpdate:
    """
    Model for tracking federated learning model updates.
    """
    id: str
    organization_id: str
    round_number: int
    timestamp: datetime
    num_samples: int
    gradient_checksum: str
    is_aggregated: bool = False


@dataclass
class ThreatIntelligence:
    """
    Model for threat intelligence data shared across organizations.
    """
    id: str
    threat_type: ThreatType
    pattern_hash: str
    first_seen: datetime
    last_seen: datetime
    occurrences: int = 1
    contributing_orgs: List[str] = field(default_factory=list)
    confidence: float = 0.0


class InMemoryDatabase:
    """
    Simple in-memory database for demo purposes.

    In production, this would be replaced with a real database
    like PostgreSQL or DynamoDB.
    """

    def __init__(self):
        self.users: List[User] = []
        self.products: List[Product] = []
        self.request_logs: List[RequestLog] = []
        self.waf_rules: List[WAFRule] = []
        self.model_updates: List[FederatedModelUpdate] = []
        self.threat_intel: List[ThreatIntelligence] = []
        self._init_sample_data()

    def _init_sample_data(self):
        """Initialize with sample data."""
        self.users = [
            User(id=1, username="alice", email="alice@example.com"),
            User(id=2, username="bob", email="bob@example.com"),
            User(id=3, username="charlie", email="charlie@example.com"),
        ]
        self.products = [
            Product(id=1, name="Widget A", description="A great widget", price=29.99, stock=100),
            Product(id=2, name="Widget B", description="An even better widget", price=49.99, stock=50),
            Product(id=3, name="Widget C", description="The ultimate widget", price=99.99, stock=25),
        ]

    def get_user(self, user_id: int) -> Optional[User]:
        """Get user by ID."""
        return next((u for u in self.users if u.id == user_id), None)

    def get_product(self, product_id: int) -> Optional[Product]:
        """Get product by ID."""
        return next((p for p in self.products if p.id == product_id), None)

    def search_products(self, query: str) -> List[Product]:
        """Search products by name."""
        query_lower = query.lower()
        return [p for p in self.products if query_lower in p.name.lower()]

    def add_request_log(self, log: RequestLog) -> None:
        """Add a request log entry."""
        self.request_logs.append(log)

    def get_recent_logs(self, limit: int = 100) -> List[RequestLog]:
        """Get recent request logs."""
        return sorted(self.request_logs, key=lambda x: x.timestamp, reverse=True)[:limit]

    def add_waf_rule(self, rule: WAFRule) -> None:
        """Add a WAF rule."""
        self.waf_rules.append(rule)

    def get_active_waf_rules(self) -> List[WAFRule]:
        """Get all active WAF rules."""
        return [r for r in self.waf_rules if r.is_active]


db = InMemoryDatabase()
